### ISSUE TITLE
support configurable smb.conf

### ISSUE THREAD

**Issue by systeemkabouter** [djjudas21/puppet-winbind#1]
Currently the module uses the compile default configuration file smb.conf . The net command manpage states that the file used can be specified with the -s flag. This is an effective way to split the managing of fileshares and authentication. 

-s|--configfile <configuration file>
    The file specified contains the configuration details required by the server. The information in this file includes server-specific information such as what printcap file to use, as well as descriptions of all the services that the server is to provide. See smb.conf for more information. The default configuration file name is determined at compile time. 

I am willing to create the PR that implements that if you are open to my suggestion.

**Comment by djjudas21** [comment]
I think this would be a useful feature. If you go ahead and implement the feature, I'll QA it in the New Year. Thanks!

**Comment by systeemkabouter** [comment]
https://github.com/djjudas21/puppet-winbind/pull/2

**Comment by djjudas21** [comment]
I'll close this too, as #2 has been accepted
